spring.application.name=Doctors

server.port=7070

#rapid.health.ai
api.key=8c1641d5dfmsh0b09c2fcecd3565p1f4824jsnd45e55f0727b


spring.security.oauth2.client.registration.google.client-id=974939808709-qsslae28mr8rg0q86lrjqhao7ajg4qbo.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Optional:
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#http://localhost:7070/login/oauth2/code/google
