spring.application.name=Doctors

server.port=7070

#rapid.health.ai
api.key=1641d5dfmsh0b09c2fcecd3565p1f4824jsnd45e55f


spring.security.oauth2.client.registration.google.client-id=removrd for security reason
spring.security.oauth2.client.registration.google.client-secret=removed for security reason
spring.security.oauth2.client.registration.google.scope=email,profile

# Optional:
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#http://localhost:7070/login/oauth2/code/google
